name: ece-6254-project
channels:
  - defaults
  - pytorch
dependencies:
  - python==3.7.13
  - cpuonly # Comment this out if you are utilizing a GPU
  - pytorch==1.10.0
  - torchvision==0.11.1
  - torchtext==0.11.1
  - numpy
  - matplotlib
  - pip
  - pip:
    - datasets
    - transformers
    - huggingface_hub
    - sklearn